# /Users/alex/.config/tmuxinator/dev.yml

name: dev
root: ~/github

windows:
  - habsida:
      root: ~/github/habsida
      layout: main-vertical
      panes:
        - 1:
  - naonow:
      root: ~/github/naonow
      layout: main-vertical
      panes:
        - server: z server
        - dashboard: z dashboard
        - admin: z admin
